apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: icondigiital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: persistent-storage
        
          csi:
            driver: blob.csi.azure.com
            readOnly: false
            volumeAttributes:
              containerName: content
            nodePublishSecretRef:
              name: azure-secret
