on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

    - name: Delete existing blobs
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode login --source ${{ secrets.STORAGE_CONTAINER_NAME }}

    - name: Upload new blobs
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode login --source Content --destination ${{ secrets.STORAGE_CONTAINER_NAME }}

    - name: Azure logout
      run: az logout
      if: always()
